export const settings = [
  {
    type: 'div',
    id: 'personlist',
    containerType: 'person',
    containerId: 'personContainer',
    containerStylelist: 'person__container',
    typeStructure: {
      main: 'section',
      firstSubtype: 'ul',
      secondSubtype: 'li',
    },
    url: '././src/data.json',
    stylelist: 'person',
    styleElement: [],
    innerHTML: '',
    dataStructure: [
      {
        type: 'div',
        id: 'firstName',
        key: 'name',
        subkey: 'firstName',
        name: 'firstName',
        stylelist: 'person__firstname',
        styleheader: 'person__filter',
        styleElement: [],
        innerHTML: '',
        subElement: {},
      },
      {
        type: 'div',
        id: 'lastName',
        key: 'name',
        subkey: 'lastName',
        name: 'lastName',
        stylelist: 'person__lastname',
        styleheader: 'person__filter',
        styleElement: [],
        innerHTML: '',
        subElement: {},
      },
      {
        type: 'div',
        id: 'about',
        key: 'about',
        subkey: '',
        name: 'about',
        stylelist: 'person__about',
        styleheader: 'person__filter',
        styleElement: [],
        innerHTML: '',
        subElement: {},
      },
      {
        type: 'div',
        id: 'eyeColor',
        key: 'eyeColor',
        subkey: '',
        name: 'eyeColor',
        stylelist: 'person__eyeColor',
        styleheader: 'person__filter',
        styleElement: [],
        innerHTML: '',
        subElement: {
          type: 'div',
          id: 'person__eyeColor',
          stylelist: 'eyeColor__component',
          styleElement: [{name: 'backgroundColor', value: 'eyeColor'}]
        },
      }
    ],
  },
  {
    type: 'div',
    id: 'aboutPerson',
    containerType: 'person',
    containerId: 'personContainer',
    containerStylelist: 'person__container',
    typeStructure: {
      main: 'div',
      firstSubtype: 'form',
      secondSubtype: 'input',
    },
    url: '',
    stylelist: 'person',
    styleElement: [],
    innerHTML: 'About selected person',
    dataStructure: [],
  },
  {
    type: 'div',
    id: 'pageList',
    containerType: 'pagelist',
    containerId: 'pagelistContainer',
    containerStylelist: 'pagelist__container',
    typeStructure: {
      main: 'div',
      firstSubtype: 'ul',
      secondSubtype: 'li',
    },
    url: '',
    stylelist: 'pagelist',
    styleElement: [],
    innerHTML: '',
    dataStructure: [],
  },
]